export type TemplateLayout = "sidebar" | "band";
export type TemplateFont = "sans" | "serif" | "mono";

export interface TemplatePalette {
  paper: string;
  text: string;
  muted: string;
  accent: string;
  headerBg: string;
  headerText: string;
  headerAccent: string;
  chipBg: string;
  chipText: string;
  chipBorder: string;
}

export interface TemplateConfig {
  id: string;
  name: string;
  description: string;
  layout: TemplateLayout;
  font: TemplateFont;
  palette: TemplatePalette;
  fontSizeScale: number;
}

export const FONT_MAP: Record<TemplateFont, { web: string; pdf: string; pdfBold: string }> = {
  sans: {
    web: "'Geist', system-ui, Arial, sans-serif",
    pdf: "Helvetica",
    pdfBold: "Helvetica-Bold",
  },
  serif: {
    web: "Georgia, 'Times New Roman', serif",
    pdf: "Times-Roman",
    pdfBold: "Times-Bold",
  },
  mono: {
    web: "'Courier New', ui-monospace, monospace",
    pdf: "Courier",
    pdfBold: "Courier-Bold",
  },
};

export const TEMPLATES: TemplateConfig[] = [
  {
    id: "modern",
    name: "Moderno",
    description: "Sidebar índigo com contato e habilidades",
    layout: "sidebar",
    font: "sans",
    palette: {
      paper: "#ffffff",
      text: "#27272a",
      muted: "#71717a",
      accent: "#4f46e5",
      headerBg: "#1e1b4b",
      headerText: "#ffffff",
      headerAccent: "#a5b4fc",
      chipBg: "#312e81",
      chipText: "#ffffff",
      chipBorder: "#4f46e5",
    },
    fontSizeScale: 1,
  },
  {
    id: "classic",
    name: "Clássico",
    description: "Coluna única com cabeçalho centralizado e serifa",
    layout: "band",
    font: "serif",
    palette: {
      paper: "#ffffff",
      text: "#1e293b",
      muted: "#64748b",
      accent: "#1e3a5f",
      headerBg: "#ffffff",
      headerText: "#1e3a5f",
      headerAccent: "#334155",
      chipBg: "#eef2f7",
      chipText: "#1e3a5f",
      chipBorder: "#e2e8f0",
    },
    fontSizeScale: 1,
  },
  {
    id: "minimal",
    name: "Minimalista",
    description: "Muito espaço em branco e preto sobre branco",
    layout: "band",
    font: "sans",
    palette: {
      paper: "#ffffff",
      text: "#18181b",
      muted: "#a1a1aa",
      accent: "#18181b",
      headerBg: "#ffffff",
      headerText: "#18181b",
      headerAccent: "#71717a",
      chipBg: "#fafafa",
      chipText: "#52525b",
      chipBorder: "#e4e4e7",
    },
    fontSizeScale: 1,
  },
  {
    id: "bold",
    name: "Ousado",
    description: "Faixa preta no topo com acentos âmbar",
    layout: "band",
    font: "sans",
    palette: {
      paper: "#ffffff",
      text: "#111827",
      muted: "#6b7280",
      accent: "#f59e0b",
      headerBg: "#111827",
      headerText: "#ffffff",
      headerAccent: "#f59e0b",
      chipBg: "#fef3c7",
      chipText: "#92400e",
      chipBorder: "#fde68a",
    },
    fontSizeScale: 1,
  },
  {
    id: "elegant",
    name: "Elegante",
    description: "Serifa refinada com tom de esmeralda",
    layout: "band",
    font: "serif",
    palette: {
      paper: "#fdfaf6",
      text: "#1c1917",
      muted: "#78716c",
      accent: "#065f46",
      headerBg: "#fdfaf6",
      headerText: "#1c1917",
      headerAccent: "#065f46",
      chipBg: "#ecfdf5",
      chipText: "#065f46",
      chipBorder: "#d1fae5",
    },
    fontSizeScale: 1,
  },
  {
    id: "creative",
    name: "Criativo",
    description: "Sidebar violeta vibrante",
    layout: "sidebar",
    font: "sans",
    palette: {
      paper: "#ffffff",
      text: "#3f3f46",
      muted: "#8b8b9e",
      accent: "#7c3aed",
      headerBg: "#7c3aed",
      headerText: "#ffffff",
      headerAccent: "#ddd6fe",
      chipBg: "#ede9fe",
      chipText: "#6d28d9",
      chipBorder: "#ddd6fe",
    },
    fontSizeScale: 1,
  },
  {
    id: "compact",
    name: "Compacto",
    description: "Denso e direto, ideal para 2 páginas a menos",
    layout: "band",
    font: "sans",
    palette: {
      paper: "#ffffff",
      text: "#334155",
      muted: "#94a3b8",
      accent: "#334155",
      headerBg: "#ffffff",
      headerText: "#0f172a",
      headerAccent: "#64748b",
      chipBg: "#f1f5f9",
      chipText: "#334155",
      chipBorder: "#e2e8f0",
    },
    fontSizeScale: 0.85,
  },
  {
    id: "tech",
    name: "Tech",
    description: "Tema escuro com acentos neon",
    layout: "band",
    font: "mono",
    palette: {
      paper: "#0f172a",
      text: "#e2e8f0",
      muted: "#64748b",
      accent: "#22d3ee",
      headerBg: "#0f172a",
      headerText: "#22d3ee",
      headerAccent: "#38bdf8",
      chipBg: "#164e63",
      chipText: "#67e8f9",
      chipBorder: "#0e7490",
    },
    fontSizeScale: 1,
  },
  {
    id: "professional",
    name: "Profissional",
    description: "Sidebar azul-marinho sóbria",
    layout: "sidebar",
    font: "sans",
    palette: {
      paper: "#ffffff",
      text: "#1f2937",
      muted: "#6b7280",
      accent: "#2563eb",
      headerBg: "#172554",
      headerText: "#ffffff",
      headerAccent: "#93c5fd",
      chipBg: "#1e3a8a",
      chipText: "#ffffff",
      chipBorder: "#3b82f6",
    },
    fontSizeScale: 1,
  },
  {
    id: "colorful",
    name: "Colorido",
    description: "Rosa vibrante com clima acolhedor",
    layout: "band",
    font: "sans",
    palette: {
      paper: "#fff7fa",
      text: "#27272a",
      muted: "#9d7a86",
      accent: "#e11d48",
      headerBg: "#e11d48",
      headerText: "#ffffff",
      headerAccent: "#fecdd3",
      chipBg: "#ffe4e6",
      chipText: "#be123c",
      chipBorder: "#fecdd3",
    },
    fontSizeScale: 1,
  },
  {
    id: "executive",
    name: "Executivo",
    description: "Azul-marinho com detalhes dourados sofisticados",
    layout: "band",
    font: "sans",
    palette: {
      paper: "#ffffff",
      text: "#1e293b",
      muted: "#64748b",
      accent: "#b45309",
      headerBg: "#0f172a",
      headerText: "#ffffff",
      headerAccent: "#e7c158",
      chipBg: "#fef3c7",
      chipText: "#92400e",
      chipBorder: "#fde68a",
    },
    fontSizeScale: 1,
  },
  {
    id: "corporate",
    name: "Corporativo",
    description: "Sidebar clara com texto azul sóbrio",
    layout: "sidebar",
    font: "sans",
    palette: {
      paper: "#ffffff",
      text: "#1f2937",
      muted: "#6b7280",
      accent: "#2563eb",
      headerBg: "#eef2f7",
      headerText: "#0f172a",
      headerAccent: "#2563eb",
      chipBg: "#eff6ff",
      chipText: "#1d4ed8",
      chipBorder: "#dbeafe",
    },
    fontSizeScale: 1,
  },
  {
    id: "navy",
    name: "Marinho",
    description: "Azul-marinho clássico com toque moderno",
    layout: "band",
    font: "sans",
    palette: {
      paper: "#f8fafc",
      text: "#1e293b",
      muted: "#64748b",
      accent: "#1d4ed8",
      headerBg: "#1e3a5f",
      headerText: "#ffffff",
      headerAccent: "#bfdbfe",
      chipBg: "#dbeafe",
      chipText: "#1e40af",
      chipBorder: "#bfdbfe",
    },
    fontSizeScale: 1,
  },
  {
    id: "graphite",
    name: "Grafite",
    description: "Sidebar grafite escuro com acentos lima",
    layout: "sidebar",
    font: "sans",
    palette: {
      paper: "#ffffff",
      text: "#27272a",
      muted: "#71717a",
      accent: "#65a30d",
      headerBg: "#27272a",
      headerText: "#fafafa",
      headerAccent: "#a3e635",
      chipBg: "#3f3f46",
      chipText: "#d4d4d8",
      chipBorder: "#52525b",
    },
    fontSizeScale: 1,
  },
  {
    id: "sunshine",
    name: "Solar",
    description: "Amarelo vibrante que transmite energia positiva",
    layout: "band",
    font: "sans",
    palette: {
      paper: "#fffbeb",
      text: "#451a03",
      muted: "#92400e",
      accent: "#f59e0b",
      headerBg: "#fbbf24",
      headerText: "#451a03",
      headerAccent: "#92400e",
      chipBg: "#fef3c7",
      chipText: "#b45309",
      chipBorder: "#fde68a",
    },
    fontSizeScale: 1,
  },
  {
    id: "terracotta",
    name: "Terracota",
    description: "Tom terroso acolhedor com serifa",
    layout: "band",
    font: "serif",
    palette: {
      paper: "#fdf6f0",
      text: "#292524",
      muted: "#a8a29e",
      accent: "#c2410c",
      headerBg: "#fdf6f0",
      headerText: "#c2410c",
      headerAccent: "#9a3412",
      chipBg: "#ffedd5",
      chipText: "#9a3412",
      chipBorder: "#fed7aa",
    },
    fontSizeScale: 1,
  },
  {
    id: "wine",
    name: "Vinho",
    description: "Bordô profundo com elegância marcante",
    layout: "band",
    font: "sans",
    palette: {
      paper: "#ffffff",
      text: "#292524",
      muted: "#78716c",
      accent: "#9f1239",
      headerBg: "#7f1d1d",
      headerText: "#ffffff",
      headerAccent: "#fecdd3",
      chipBg: "#ffe4e6",
      chipText: "#be123c",
      chipBorder: "#fecdd3",
    },
    fontSizeScale: 1,
  },
  {
    id: "midnight",
    name: "Meia-noite",
    description: "Sidebar preta com acentos fúcsia",
    layout: "sidebar",
    font: "sans",
    palette: {
      paper: "#ffffff",
      text: "#18181b",
      muted: "#71717a",
      accent: "#d946ef",
      headerBg: "#0a0a0a",
      headerText: "#f4f4f5",
      headerAccent: "#f0abfc",
      chipBg: "#18181b",
      chipText: "#f0abfc",
      chipBorder: "#3f3f46",
    },
    fontSizeScale: 1,
  },
  {
    id: "ice",
    name: "Gelo",
    description: "Branco gelo com azul-céu refrescante",
    layout: "band",
    font: "sans",
    palette: {
      paper: "#f8fafc",
      text: "#334155",
      muted: "#94a3b8",
      accent: "#0284c7",
      headerBg: "#ffffff",
      headerText: "#0c4a6e",
      headerAccent: "#0284c7",
      chipBg: "#e0f2fe",
      chipText: "#0369a1",
      chipBorder: "#bae6fd",
    },
    fontSizeScale: 1,
  },
  {
    id: "retro",
    name: "Retrô",
    description: "Creme vintage com serifa e toque mostarda",
    layout: "band",
    font: "serif",
    palette: {
      paper: "#faf6f0",
      text: "#292524",
      muted: "#a8a29e",
      accent: "#a16207",
      headerBg: "#f5efe4",
      headerText: "#3f2d1e",
      headerAccent: "#a16207",
      chipBg: "#faf1e0",
      chipText: "#854d0e",
      chipBorder: "#eaddc0",
    },
    fontSizeScale: 1,
  },
];

export function getTemplate(id: string | undefined): TemplateConfig {
  return TEMPLATES.find((t) => t.id === id) ?? TEMPLATES[0];
}